name: CI (e2e)

on:
  push:
    branches:    
    - main 
  pull_request_target:
    branches: [ main ]

  workflow_dispatch:

permissions: write-all

jobs:
  import-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        module-type: [commonjs, esm]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: tests/${{ matrix.module-type }}/yarn.lock
      - name: Test
        working-directory: tests/${{ matrix.module-type }}
        run: yarn install && yarn build && yarn test
