name: CI (e2e)

on:
  push:
    branches:    
    - main 
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions: write-all

jobs:
  import-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        module-type: [commonjs, esm]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: |
            - recursive: true
              cwd: tests/${{ matrix.module-type }}
              args: [--no-frozen-lockfile]
          package_json_file: tests/${{ matrix.module-type }}/package.json
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Test
        working-directory: tests/${{ matrix.module-type }}
        run: pnpm build && pnpm test
