name: Automatic release
on:
  release:
    types:
      - published

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: write

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v4
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          scope       : 'appstore-connect-jwt-generator-core'
          always-auth : true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: |
            - recursive: true
              cwd: package
              args: [--no-frozen-lockfile]
          package_json_file: package/package.json

      - name: Can Publish
        run : npx can-npm-publish --verbose
        working-directory: package
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run : pnpm build
        working-directory: package
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run : npm publish --access=public
        working-directory: package
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}